### PR TITLE
Message pushing and several fixes around the code

### PR DESCRIPTION
**Pull request by rikvdh**
@jraats and @xor-gate can you both review?

### CODE REVIEW

**Comment by xor-gate** [comment]
Travis build is broken

**Comment by xor-gate** [comment]
Maybe add a `doc.go` file (see example https://github.com/gorilla/mux/blob/master/doc.go, https://godoc.org/github.com/gorilla/mux)

**Comment by jraats** [comment]
LGTM

**Review by xor-gate — APPROVED** [review]
LGTM

**Review by jraats — APPROVED** [review]

**Pull request merged**
